var exec = require('child_process').exec;

desc('Build everything');
task('default',['css'],function() {
	console.log("Done");
});

desc('Run unit tests');
task('test', [], function() {
	console.log("Running tests");
	jake.exec("nodeunit tests", { printStdout:true, printStderr: true});
});

desc('Migrate');
task('migrate', [], function() {
	require("./migrate/automigrate.js");
});

desc('Build css');
task('css', [], function(params) {
	exec("lessc less/style.less ../public/css/style.css", { printStdout: true, printStderr: true });
	exec("lessc -x less/style.less ../public/css/style.min.css", { printStdout: true, printStderr: true });
});


